---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fatboar
  template:
    metadata:
      labels:
        app: fatboar
    spec:
      imagePullSecrets:
        - name: regsecret
      containers:
        - name: fatboar-jeux
          image: $IMAGE_NAME
          ports:
            - containerPort: 80
              name: web
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            timeoutSeconds: 5
            failureThreshold: 12
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: NodePort
  selector:
    app: fatboar
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web
spec:
  rules:
    - host: 
      http:
        paths:
          - path: /jeux
            backend:
              serviceName: web
              servicePort: 80